apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: idq3eun75-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/idq3eun75-java-springboot-gitops